import path from "node:path";
import { parseJsonObjectStrict, sha256 } from "./active_review_io.mjs";

const SHEETS = ["短片清单", "人工动作", "候选提示", "标签说明"];
const REVIEWS = ["background", "serve", "receive", "set", "attack", "block", "dig", "free_ball"];
const SIDES = ["far", "near"];
const VIS = ["direct_clear", "direct_partial", "fully_occluded", "off_camera", "unresolved"];
const BASIS = ["direct_video", "referee_signal", "scoreboard", "sequence_context", "mixed"];
const OUTCOMES = ["continued", "point_won", "point_lost", "unknown"];
const STATUS = ["observed_or_inferred", "unresolved"];
const EVENTS = ["occlusion", "off_camera"];
const SCOPES = ["timed", "clip_bounds"];
const PARTICIPATION = ["primary_actor", "block_attempt", "support"];
const TOUCH = ["touched", "no_touch", "unknown"];
const ASSIGNMENT = ["confirmed", "candidate", "unresolved"];
const EVIDENCE_KIND = ["manual_review", "track", "jersey_ocr", "roster"];
const ROOT_KEYS = ["format", "format_version", "review_set_key", "batch_id", "round_id", "selection", "workbook", "video", "workbook_compatibility", "action_overrides", "supplemental_actions", "outcome_observations", "visibility_observations", "action_participants"];
const COMP_KEYS = ["trimmed_banner_cells", "shared_formula_ranges", "validation_import_gaps", "read_only_repairs"];

function fail(p, msg = "is invalid.") { throw new Error(`Evidence override ${p} ${msg}`); }
function fieldPath(p, k) { return p ? `${p}.${k}` : k; }
function obj(v, p, keys) { if (!v || typeof v !== "object" || Array.isArray(v)) fail(p); for (const k of Object.keys(v)) if (!keys.includes(k)) fail(fieldPath(p, k), "is unknown."); }
function req(o, k, p) { if (!Object.prototype.hasOwnProperty.call(o, k)) fail(fieldPath(p, k), "is missing."); return o[k]; }
function text(v, p) { if (typeof v !== "string") fail(p); return v; }
function nonempty(v, p) { text(v, p); if (!v.trim() || /[\u0000-\u001f]/.test(v)) fail(p); return v; }
function integer(v, p, positive = false) { if (typeof v !== "number" || !Number.isFinite(v) || !Number.isInteger(v) || (positive ? v <= 0 : v < 0)) fail(p); return v; }
function nullableInteger(v, p) { if (v !== null) integer(v, p); return v; }
function enumValue(v, p, values) { if (!values.includes(v)) fail(p); return v; }
function nullableEnum(v, p, values) { if (v !== null) enumValue(v, p, values); return v; }
function hash(v, p) { if (typeof v !== "string" || !/^[0-9a-f]{64}$/.test(v)) fail(p); return v; }
function repoPath(v, p, root) {
  nonempty(v, p); const win = /^[A-Za-z]:[\\/]/.test(String(root)) || /^[A-Za-z]:[\\/]/.test(String(v)); const api = win ? path.win32 : path; if (api.isAbsolute(v) || /^[A-Za-z]:[\\/]/.test(String(v))) fail(p, "is not a repository-relative POSIX path."); const absRoot = api.resolve(root); const abs = api.resolve(absRoot, v); const rel = (api.relative(absRoot, abs)).split(api.sep).join("/");
  if (v.includes("\\") && !win) fail(p); if (!rel || rel === "." || rel.startsWith("../") || rel === ".." || rel.split("/").some((s) => !s || s === "." || s === "..") || rel !== v) fail(p, "is not a repository-relative POSIX path.");
  return rel;
}
function suppliedRepoPath(v, p, root) { const win = /^[A-Za-z]:[\\/]/.test(String(root)) || /^[A-Za-z]:[\\/]/.test(String(v)); const api = win ? path.win32 : path; const absRoot = api.resolve(root); const abs = api.resolve(absRoot, v); const rel = api.relative(absRoot, abs).split(api.sep).join("/"); if (!rel || rel === "." || rel.startsWith("../") || rel === "..") fail(p, "is outside the repository."); return rel; }
function binding(v, p, root) { obj(v, p, ["path", "sha256"]); const out = { path: repoPath(req(v, "path", p), `${p}.path`, root), sha256: hash(req(v, "sha256", p), `${p}.sha256`) }; return out; }
function exactObject(v, p, keys) { obj(v, p, keys); return v; }
function a1(v, p, range = false) { nonempty(v, p); const re = range ? /^[A-Z]+[1-9][0-9]*:[A-Z]+[1-9][0-9]*$/ : /^[A-Z]+[1-9][0-9]*$/; if (!re.test(v)) fail(p); }
function finiteNumber(v, p) { if (typeof v !== "number" || !Number.isFinite(v)) fail(p); }
function confidence(v, p, nullable = true) { if (nullable && v === null) return; finiteNumber(v, p); if (v < 0 || v > 1) fail(p); }

function validateCompatibility(c, p, selection, root) {
  obj(c, p, COMP_KEYS); const out = {};
  const banners = req(c, "trimmed_banner_cells", p); if (!Array.isArray(banners)) fail(`${p}.trimmed_banner_cells`); out.trimmedBannerCells = banners.map((x, i) => { const q = `${p}.trimmed_banner_cells[${i}]`; obj(x, q, ["sheet", "cell", "expected_value", "actual_value"]); const sheet = enumValue(req(x, "sheet", q), `${q}.sheet`, SHEETS); const cell = req(x, "cell", q); a1(cell, `${q}.cell`); const expected = text(req(x, "expected_value", q), `${q}.expected_value`); const actual = text(req(x, "actual_value", q), `${q}.actual_value`); if (actual !== expected.trimEnd() || actual === expected) fail(`${q}.actual_value`); return { sheet, cell, expected_value: expected, actual_value: actual }; });
  const dup = (arr, key, pfx) => { const s = new Set(); for (const x of arr) { const k = key(x); if (s.has(k)) fail(pfx, "contains duplicate target."); s.add(k); } };
  dup(out.trimmedBannerCells, x => `${x.sheet}|${x.cell}`, `${p}.trimmed_banner_cells`);
  const formulas = req(c, "shared_formula_ranges", p); if (!Array.isArray(formulas)) fail(`${p}.shared_formula_ranges`); out.sharedFormulaRanges = formulas.map((x, i) => { const q = `${p}.shared_formula_ranges[${i}]`; obj(x, q, ["sheet", "range", "block_size", "expected_display_value"]); return { sheet: enumValue(req(x, "sheet", q), `${q}.sheet`, SHEETS), range: (a1(req(x, "range", q), `${q}.range`, true), x.range), block_size: integer(req(x, "block_size", q), `${q}.block_size`, true), expected_display_value: nonempty(req(x, "expected_display_value", q), `${q}.expected_display_value`) }; });
  dup(out.sharedFormulaRanges, x => `${x.sheet}|${x.range}`, `${p}.shared_formula_ranges`);
  const gaps = req(c, "validation_import_gaps", p); if (!Array.isArray(gaps)) fail(`${p}.validation_import_gaps`); out.validationImportGaps = gaps.map((x, i) => { const q = `${p}.validation_import_gaps[${i}]`; obj(x, q, ["sheet", "range", "validation_kind", "expected_rule"]); const sheet = req(x, "sheet", q); if (sheet !== "人工动作") fail(`${q}.sheet`); const range = req(x, "range", q); if (!["E4:E483", "F4:G483", "H4:H483"].includes(range)) fail(`${q}.range`); const kind = enumValue(req(x, "validation_kind", q), `${q}.validation_kind`, ["list", "whole"]); const er = req(x, "expected_rule", q); const rules = { "E4:E483": { type: "list", values: REVIEWS.slice(0, 7) }, "F4:G483": { type: "whole", operator: "greaterThanOrEqual", formula1: 0 }, "H4:H483": { type: "list", values: SIDES } }; const expected = rules[range]; if (!er || typeof er !== "object" || Array.isArray(er) || Object.keys(er).length !== Object.keys(expected).length || Object.keys(expected).some(k => !Object.prototype.hasOwnProperty.call(er, k) || JSON.stringify(er[k]) !== JSON.stringify(expected[k])) || (range === "E4:E483" && kind !== "list") || (range === "F4:G483" && kind !== "whole") || (range === "H4:H483" && kind !== "list")) fail(`${q}.expected_rule`); return { sheet, range, validation_kind: kind, expected_rule: er }; });
  dup(out.validationImportGaps, x => `${x.sheet}|${x.range}`, `${p}.validation_import_gaps`);
  const repairs = req(c, "read_only_repairs", p); if (!Array.isArray(repairs)) fail(`${p}.read_only_repairs`); out.readOnlyRepairs = repairs.map((x, i) => { const q = `${p}.read_only_repairs[${i}]`; obj(x, q, ["clip_id", "source_action_slot", "sheet", "cell", "field", "original_value", "normalized_value", "reason"]); const clip = nonempty(req(x, "clip_id", q), `${q}.clip_id`); const clipIndex = selection.clips?.findIndex(c => c.clip_id === clip) ?? -1; if (clipIndex < 0) fail(`${q}.clip_id`, "does not name a selected clip."); const slot = integer(req(x, "source_action_slot", q), `${q}.source_action_slot`); if (slot < 1 || slot > 12) fail(`${q}.source_action_slot`); if (req(x, "sheet", q) !== "人工动作" || req(x, "field", q) !== "clip_id") fail(q); const cell = req(x, "cell", q); a1(cell, `${q}.cell`); if (cell !== `A${4 + clipIndex * 12 + slot - 1}`) fail(`${q}.cell`); if (req(x, "original_value", q) !== null) fail(`${q}.original_value`); if (req(x, "normalized_value", q) !== clip) fail(`${q}.normalized_value`); nonempty(req(x, "reason", q), `${q}.reason`); return x; });
  dup(out.readOnlyRepairs, x => `${x.clip_id}|${x.source_action_slot}|${x.field}`, `${p}.read_only_repairs`); return out;
}

function expectedSource(v, p) { obj(v, p, ["review_label", "relative_start_seconds", "relative_end_seconds", "team_side", "note"]); const label = enumValue(req(v, "review_label", p), `${p}.review_label`, REVIEWS); const start = nullableInteger(req(v, "relative_start_seconds", p), `${p}.relative_start_seconds`); const end = nullableInteger(req(v, "relative_end_seconds", p), `${p}.relative_end_seconds`); if ((start === null) !== (end === null) || (start !== null && start >= end)) fail(p); return { review_label: label, relative_start_seconds: start, relative_end_seconds: end, team_side: nullableEnum(req(v, "team_side", p), `${p}.team_side`, SIDES), note: req(v, "note", p) === null ? null : text(v.note, `${p}.note`) }; }
function actionOverride(v, p) { obj(v, p, ["action_ref", "expected_source", "replacement_review_label", "visibility", "evidence_basis", "replacement_note", "reason"]); const ref = nonempty(req(v, "action_ref", p), `${p}.action_ref`); if (!/^.+\/action-[0-9]{3}$/.test(ref)) fail(`${p}.action_ref`); const out = { action_ref: ref, expected_source: expectedSource(req(v, "expected_source", p), `${p}.expected_source`), replacement_review_label: nullableEnum(req(v, "replacement_review_label", p), `${p}.replacement_review_label`, REVIEWS), visibility: nullableEnum(req(v, "visibility", p), `${p}.visibility`, VIS), evidence_basis: nullableEnum(req(v, "evidence_basis", p), `${p}.evidence_basis`, BASIS), replacement_note: req(v, "replacement_note", p) === null ? null : text(v.replacement_note, `${p}.replacement_note`), reason: nonempty(req(v, "reason", p), `${p}.reason`) }; if (out.replacement_review_label === null && out.visibility === null && out.evidence_basis === null && out.replacement_note === null) fail(p); return out; }
function supplemental(v, p) { obj(v, p, ["supplemental_index", "clip_id", "review_label", "relative_start_seconds", "relative_end_seconds", "team_side", "visibility", "evidence_basis", "interval_scope", "note", "reason"]); const out = { supplemental_index: integer(req(v, "supplemental_index", p), `${p}.supplemental_index`, true), clip_id: nonempty(req(v, "clip_id", p), `${p}.clip_id`), review_label: enumValue(req(v, "review_label", p), `${p}.review_label`, REVIEWS), relative_start_seconds: nullableInteger(req(v, "relative_start_seconds", p), `${p}.relative_start_seconds`), relative_end_seconds: nullableInteger(req(v, "relative_end_seconds", p), `${p}.relative_end_seconds`), team_side: enumValue(req(v, "team_side", p), `${p}.team_side`, SIDES), visibility: enumValue(req(v, "visibility", p), `${p}.visibility`, VIS), evidence_basis: enumValue(req(v, "evidence_basis", p), `${p}.evidence_basis`, BASIS), interval_scope: enumValue(req(v, "interval_scope", p), `${p}.interval_scope`, SCOPES), note: text(req(v, "note", p), `${p}.note`), reason: nonempty(req(v, "reason", p), `${p}.reason`) }; if (out.interval_scope === "timed" ? (out.relative_start_seconds === null || out.relative_end_seconds === null || out.relative_start_seconds >= out.relative_end_seconds) : (out.relative_start_seconds !== null || out.relative_end_seconds !== null || !["fully_occluded", "off_camera", "unresolved"].includes(out.visibility))) fail(p); if (out.interval_scope === "clip_bounds" && out.review_label === "background") fail(p); return out; }
function outcome(v, p) { obj(v, p, ["outcome_index", "related_action_refs", "outcome", "result_type", "evidence_basis", "status", "note"]); const refs = req(v, "related_action_refs", p); if (!Array.isArray(refs) || refs.length === 0 || refs.some((r, i) => !nonempty(r, `${p}.related_action_refs[${i}]`))) fail(`${p}.related_action_refs`); const result = req(v, "result_type", p); if (result !== null && (typeof result !== "string" || !/^[a-z][a-z0-9_]{0,63}$/.test(result))) fail(`${p}.result_type`); const out = { outcome_index: integer(req(v, "outcome_index", p), `${p}.outcome_index`, true), related_action_refs: refs, outcome: enumValue(req(v, "outcome", p), `${p}.outcome`, OUTCOMES), result_type: result, evidence_basis: enumValue(req(v, "evidence_basis", p), `${p}.evidence_basis`, BASIS), status: enumValue(req(v, "status", p), `${p}.status`, STATUS), note: text(req(v, "note", p), `${p}.note`) }; if (out.status === "unresolved" && (out.outcome !== "unknown" || out.result_type !== null)) fail(p); return out; }
function visibility(v, p) { obj(v, p, ["visibility_index", "event_kind", "clip_id", "team_side", "relative_start_seconds", "relative_end_seconds", "interval_scope", "related_action_refs", "note", "reason"]); const out = { visibility_index: integer(req(v, "visibility_index", p), `${p}.visibility_index`, true), event_kind: enumValue(req(v, "event_kind", p), `${p}.event_kind`, EVENTS), clip_id: nonempty(req(v, "clip_id", p), `${p}.clip_id`), team_side: enumValue(req(v, "team_side", p), `${p}.team_side`, SIDES), relative_start_seconds: nullableInteger(req(v, "relative_start_seconds", p), `${p}.relative_start_seconds`), relative_end_seconds: nullableInteger(req(v, "relative_end_seconds", p), `${p}.relative_end_seconds`), interval_scope: enumValue(req(v, "interval_scope", p), `${p}.interval_scope`, SCOPES), related_action_refs: req(v, "related_action_refs", p), note: text(req(v, "note", p), `${p}.note`), reason: nonempty(req(v, "reason", p), `${p}.reason`) }; if (!Array.isArray(out.related_action_refs) || out.related_action_refs.length === 0 || out.related_action_refs.some((r, i) => !nonempty(r, `${p}.related_action_refs[${i}]`))) fail(`${p}.related_action_refs`); if (out.interval_scope === "timed" ? (out.relative_start_seconds === null || out.relative_end_seconds === null || out.relative_start_seconds >= out.relative_end_seconds) : (out.relative_start_seconds !== null || out.relative_end_seconds !== null)) fail(p); return out; }
function participant(v, p) { obj(v, p, ["action_ref", "track_id", "identity_ref", "player_number", "participation", "touch_status", "assignment_status", "assignment_confidence", "evidence"]); const out = { action_ref: nonempty(req(v, "action_ref", p), `${p}.action_ref`), track_id: req(v, "track_id", p) === null ? null : nonempty(v.track_id, `${p}.track_id`), identity_ref: req(v, "identity_ref", p) === null ? null : nonempty(v.identity_ref, `${p}.identity_ref`), player_number: req(v, "player_number", p) === null ? null : nonempty(v.player_number, `${p}.player_number`), participation: enumValue(req(v, "participation", p), `${p}.participation`, PARTICIPATION), touch_status: enumValue(req(v, "touch_status", p), `${p}.touch_status`, TOUCH), assignment_status: enumValue(req(v, "assignment_status", p), `${p}.assignment_status`, ASSIGNMENT), assignment_confidence: req(v, "assignment_confidence", p) === null ? null : (confidence(v.assignment_confidence, `${p}.assignment_confidence`, false), v.assignment_confidence), evidence: req(v, "evidence", p) }; if (!Array.isArray(out.evidence)) fail(`${p}.evidence`); out.evidence = out.evidence.map((e, i) => { const q = `${p}.evidence[${i}]`; obj(e, q, ["kind", "source_ref", "value", "confidence"]); return { kind: enumValue(req(e, "kind", q), `${q}.kind`, EVIDENCE_KIND), source_ref: nonempty(req(e, "source_ref", q), `${q}.source_ref`), value: nonempty(req(e, "value", q), `${q}.value`), confidence: req(e, "confidence", q) === null ? null : (confidence(e.confidence, `${q}.confidence`, false), e.confidence) }; }); if (out.assignment_status === "confirmed" && (out.identity_ref === null || out.player_number === null || out.assignment_confidence === null)) fail(p); if (out.assignment_status === "candidate" && (out.assignment_confidence === null || [out.track_id, out.identity_ref, out.player_number].every(x => x === null))) fail(p); if (out.assignment_status === "unresolved" && (out.identity_ref !== null || out.player_number !== null || out.assignment_confidence !== null)) fail(p); return out; }

export async function loadEvidenceOverrideEnvelope(overridePath, { overrideBytes, selection, selectionPath, selectionBytes, workbookPath, workbookBytes, repoRoot = process.cwd() }) {
  if (!(overrideBytes instanceof Uint8Array) || !(selectionBytes instanceof Uint8Array) || !(workbookBytes instanceof Uint8Array)) throw new Error("Evidence override snapshots must be UTF-8 bytes.");
  const root = path.resolve(repoRoot); const payload = parseJsonObjectStrict(overrideBytes, "Evidence override"); obj(payload, "", ROOT_KEYS);
  if (payload.format !== "spiketrace.active-review-evidence-overrides") fail("format"); if (payload.format_version !== 1 || typeof payload.format_version !== "number" || !Number.isInteger(payload.format_version)) fail("format_version");
  const batch = nonempty(req(selection, "batch_id", "selection"), "selection.batch_id"); const round = nonempty(req(selection, "round_id", "selection"), "selection.round_id"); nonempty(payload.review_set_key, "review_set_key"); if (payload.batch_id !== batch) fail("batch_id"); if (payload.round_id !== round || !/^round-[0-9]{2}$/.test(payload.round_id)) fail("round_id"); if (!/^[^/]+\/round-[0-9]{2}$/.test(payload.review_set_key)) fail("review_set_key");
  const sel = binding(req(payload, "selection", ""), "selection", root); const wb = binding(req(payload, "workbook", ""), "workbook", root); const vid = binding(req(payload, "video", ""), "video", root);
  const expectedSelPath = suppliedRepoPath(selectionPath, "selectionPath", root); const expectedWbPath = suppliedRepoPath(workbookPath, "workbookPath", root); if (sel.path !== expectedSelPath || sel.sha256 !== sha256(selectionBytes)) fail("selection", "does not match supplied snapshot."); if (wb.path !== expectedWbPath || wb.sha256 !== sha256(workbookBytes)) fail("workbook", "does not match supplied snapshot."); if (vid.path !== selection.video?.path || vid.sha256 !== selection.video?.sha256) fail("video", "does not match selection.");
  const compatibility = validateCompatibility(req(payload, "workbook_compatibility", ""), "workbook_compatibility", selection, root);
  const actionOverrides = req(payload, "action_overrides", ""); if (!Array.isArray(actionOverrides)) fail("action_overrides"); const actions = actionOverrides.map((x, i) => { const value = actionOverride(x, `action_overrides[${i}]`); const match = value.action_ref.match(/^([^/]+)\/action-(\d{3})$/); if (!match || Number(match[2]) < 1 || Number(match[2]) > 12) fail(`action_overrides[${i}].action_ref`); const clipId = match[1]; const clip = selection.clips?.find(c => c.clip_id === clipId); if (!clip) fail(`action_overrides[${i}].action_ref`); const source = value.expected_source; if (source.review_label !== "background" && (source.relative_start_seconds === null || source.relative_end_seconds === null)) fail(`action_overrides[${i}].expected_source`, "requires timed values for non-background."); if (source.relative_end_seconds !== null && source.relative_end_seconds > clip.duration_seconds) fail(`action_overrides[${i}].expected_source.relative_end_seconds`); return value; }); const refs = new Set(); for (const x of actions) { if (refs.has(x.action_ref)) fail("action_overrides", "contains duplicate target."); refs.add(x.action_ref); }
  const sups = req(payload, "supplemental_actions", ""); if (!Array.isArray(sups)) fail("supplemental_actions"); const supplementalActions = sups.map((x, i) => { const value = supplemental(x, `supplemental_actions[${i}]`); const clip = selection.clips?.find(c => c.clip_id === value.clip_id); if (!clip) fail(`supplemental_actions[${i}].clip_id`, "does not name a selected clip."); if (value.interval_scope === "timed" && value.relative_end_seconds > clip.duration_seconds) fail(`supplemental_actions[${i}].relative_end_seconds`); return value; });
  const outcomes = req(payload, "outcome_observations", ""); if (!Array.isArray(outcomes)) fail("outcome_observations"); const outcomeObservations = outcomes.map((x, i) => outcome(x, `outcome_observations[${i}]`));
  const vis = req(payload, "visibility_observations", ""); if (!Array.isArray(vis)) fail("visibility_observations"); const visibilityObservations = vis.map((x, i) => { const value = visibility(x, `visibility_observations[${i}]`); const clip = selection.clips?.find(c => c.clip_id === value.clip_id); if (!clip) fail(`visibility_observations[${i}].clip_id`, "does not name a selected clip."); if (value.interval_scope === "timed" && value.relative_end_seconds > clip.duration_seconds) fail(`visibility_observations[${i}].relative_end_seconds`); return value; });
  const parts = req(payload, "action_participants", ""); if (!Array.isArray(parts)) fail("action_participants"); const participants = parts.map((x, i) => participant(x, `action_participants[${i}]`));
  const overrideRepoPath = suppliedRepoPath(overridePath, "overridePath", root); return { payload, overridePath: path.resolve(overridePath), overrideRepoPath, overrideBytes, overrideSha256: sha256(overrideBytes), selectionBinding: sel, workbookBinding: wb, videoBinding: vid };
}

export function validateEvidenceOverrideReferences(boundOverrides, { selection, canonicalActionRows }) {
  const payload = boundOverrides.payload;
  const actionOverrides = payload.action_overrides;
  const supplementalActions = payload.supplemental_actions;
  const outcomes = payload.outcome_observations;
  const visibilityObservations = payload.visibility_observations;
  const participants = payload.action_participants;
  const sourceRepairs = payload.workbook_compatibility.read_only_repairs;
  const clips = new Map((selection?.clips ?? []).map(c => [c.clip_id, c])); const sourceRefs = new Set(); const sourceMap = new Map();
  for (const [i, row] of (canonicalActionRows ?? []).entries()) { const raw = row?.raw_values ?? {}; const clip = row?.clip_id ?? raw?.clip_id; const slot = row?.source_action_slot ?? row?.slot ?? (i % 12) + 1; const ref = row?.action_ref ?? (clip ? `${clip}/action-${String(slot).padStart(3, "0")}` : null); if (ref) { sourceRefs.add(ref); sourceMap.set(ref, { row, raw, clip, slot }); } }
  for (const [i, x] of actionOverrides.entries()) { const m = x.action_ref.match(/^(.+)\/action-(\d{3})$/); const source = sourceMap.get(x.action_ref); if (!clips.has(m[1]) || !sourceRefs.has(x.action_ref)) fail(`action_overrides[${i}].action_ref`, "does not resolve to a canonical action row."); const expected = x.expected_source; const raw = source.raw; const fields = ["review_label", "relative_start_seconds", "relative_end_seconds", "team_side", "note"]; for (const field of fields) if (raw[field] !== expected[field]) fail(`action_overrides[${i}].expected_source.${field}`, "does not match the canonical raw value."); }
  const all = new Set(sourceRefs); const actionLocations = new Map([...sourceMap.entries()].map(([ref, source]) => [ref, { clip_id: source.clip, team_side: source.row?.normalized_values?.team_side ?? source.raw?.team_side }])); const byClip = new Map(); for (const [i, x] of supplementalActions.entries()) { if (!clips.has(x.clip_id)) fail(`supplemental_actions[${i}].clip_id`, "does not name a selected clip."); const arr = byClip.get(x.clip_id) ?? []; arr.push(x); byClip.set(x.clip_id, arr); const ref = `${x.clip_id}/supplemental-${String(x.supplemental_index).padStart(3, "0")}`; if (all.has(ref)) fail(`supplemental_actions[${i}]`); all.add(ref); actionLocations.set(ref, { clip_id: x.clip_id, team_side: x.team_side }); }
  for (const [clip, arr] of byClip) { arr.forEach((x, i) => { if (x.supplemental_index !== i + 1) fail("supplemental_actions", "indexes must be contiguous per clip."); }); }
  const checkRefs = (refs, p) => { const seen = new Set(); for (const [i, r] of refs.entries()) { if (seen.has(r)) fail(`${p}[${i}]`, "contains duplicate reference."); seen.add(r); if (!all.has(r)) fail(`${p}[${i}]`, "does not resolve to an action."); } };
  outcomes.forEach((x, i) => { if (x.outcome_index !== i + 1) fail(`outcome_observations[${i}].outcome_index`, "must be contiguous."); checkRefs(x.related_action_refs, `outcome_observations[${i}].related_action_refs`); }); visibilityObservations.forEach((x, i) => { if (x.visibility_index !== i + 1) fail(`visibility_observations[${i}].visibility_index`, "must be contiguous."); if (!clips.has(x.clip_id)) fail(`visibility_observations[${i}].clip_id`); checkRefs(x.related_action_refs, `visibility_observations[${i}].related_action_refs`); for (const ref of x.related_action_refs) { const action = actionLocations.get(ref); if (action?.clip_id !== x.clip_id || action?.team_side !== x.team_side) fail(`visibility_observations[${i}].related_action_refs`, "must name actions from the same clip and side."); } });
  const seenParts = new Set(); const tracks = new Map(); const identities = new Map(); for (const [i, x] of participants.entries()) { if (!all.has(x.action_ref)) fail(`action_participants[${i}].action_ref`, "does not resolve to an action."); const evidenceKeys = new Set(); for (const [j, e] of x.evidence.entries()) { const ek = `${e.kind}|${e.source_ref}|${e.value}`; if (evidenceKeys.has(ek)) fail(`action_participants[${i}].evidence[${j}]`, "duplicates evidence."); evidenceKeys.add(ek); } const key = `${x.action_ref}|${x.track_id}|${x.identity_ref}|${x.player_number}|${x.participation}|${x.touch_status}|${x.assignment_status}|${x.assignment_confidence}`; if (seenParts.has(key)) fail(`action_participants[${i}]`, "duplicates a participant relation."); seenParts.add(key); if (x.track_id !== null) { const k = `${x.action_ref}|${x.track_id}`; if (tracks.has(k)) fail(`action_participants[${i}].track_id`, "duplicates a track ID within the action."); tracks.set(k, true); } if (x.identity_ref !== null) { const k = `${x.action_ref}|${x.identity_ref}`; if (identities.has(k)) fail(`action_participants[${i}].identity_ref`, "duplicates an identity reference within the action."); identities.set(k, true); } }
  return { bound: boundOverrides, sourceRepairs, actionOverrides, supplementalActions, outcomes, visibilityObservations, participants };
}
